name: secret_key_scrypt_generator
description: A Dart CLI to obfuscate a secret key and generate a Dart file that
  can safely reconstruct it at runtime.
version: 0.0.1
repository: https://anonimeact@github.com/anonimeact/secrectkey.git
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  secure_compressor: ^1.0.10
# path: ^1.8.0
executables:
  secretkey: secret_key_scrypt_generator

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
