name: secret_key_scrypt_generator
description: A Dart CLI to obfuscate a secret key and generate a Dart file that
  can safely reconstruct it at runtime.
version: 1.0.0
homepage: https://github.com/anonimeact/secrectkey
repository: https://github.com/anonimeact/secrectkey
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  encrypt: ^5.0.3
  
executables:
  secretkey: secret_key_scrypt_generator

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

platforms:
  ? android
  ? ios
  ? web
