import 'dart:convert';
import 'dart:io';

class Obfuscator {
  
  /// Generate an obfuscated key function and append it to lib/secret.dart.
  /// If lib/secret.dart does not exist, create a skeleton class.
  /// The generated function will return the original key when called.
  /// The key can be provided as a plaintext string or read from a file.
  /// The obfuscation is done using a simple XOR with a fixed mask.

  static void generate(List<String> args) {
    final input = args[1];
    final functionName = args[2];

    String key;

    // Kalau input adalah file yang ada, baca persis isinya (multiline supported)
    final file = File(input);
    if (file.existsSync()) {
      key = file.readAsStringSync();
      print("📂 Loaded key from file: $input");
    } else {
      key = input;
      print("🔑 Using inline key: $input");
    }

    const mask = 137; // XOR mask
    final encoded = utf8.encode(key);
    final obfuscated = encoded.map((b) => b ^ mask).toList();

    // Bagi ke chunk ukuran 4 byte
    const chunkSize = 4;
    final chunks = <List<int>>[];
    for (var i = 0; i < obfuscated.length; i += chunkSize) {
      chunks.add(obfuscated.sublist(i, (i + chunkSize).clamp(0, obfuscated.length)));
    }

    // Path file target
    final secretFile = File("lib/secret.dart");

    // Kalau file belum ada → buat skeleton class
    if (!secretFile.existsSync()) {
      secretFile.writeAsStringSync("""
  import 'dart:convert';
  
  /// Auto-generated by secret_key_secrect_generator.
  /// Never manually edit this file!
  class SecretKey {
  static const _mask = $mask;
  }
  """);
    }

    // Tambahkan method baru
    final method =
        """
  
  static Future<String> $functionName() async {
    const _chunks = <List<int>>${jsonEncode(chunks)};
    final flat = _chunks.expand((e) => e).map((b) => b ^ _mask).toList();
    return utf8.decode(flat);
  }
  """;

    // Append ke class SecretKey
    var content = secretFile.readAsStringSync();
    content = content.replaceFirst("}", "$method}");
    secretFile.writeAsStringSync(content);

    print("✅ Added function $functionName() to lib/secret.dart");
  }
}
